Update jitpack_build.yml

diff --git a/.github/workflows/jitpack_build.yml b/.github/workflows/jitpack_build.yml
--- a/.github/workflows/jitpack_build.yml
+++ b/.github/workflows/jitpack_build.yml
@@ -17,10 +17,21 @@ jobs:
         PACKAGES_URL="https://jitpack.io/com/github/${GITHUB_REPOSITORY}/${GITHUB_REF#refs/tags/}/"
         echo "Triggering JitPack build"
         
+        # Try the URL 3 times before failing
+        count=1
+        until [[ $count -gt 3 ]] || [[ $( curl -sS ${PACKAGES_URL} | wc -l | xargs) -gt 1 ]]; do
+          echo "Attempt ${count}/3"
+          FILES=$(curl -w "\n" -sS --max-time 900 ${PACKAGES_URL})
+          let count+=1
+          sleep 5
+        done
+        
         echo "::group::Files Available"
-        curl -w "\n" -sS --max-time 900 ${PACKAGES_URL}
+        echo ${FILES}
         echo "::endgroup::"
         
-        if [[ ! $( curl -sS ${PACKAGES_URL} | wc -l | xargs) -gt 1 ]]; then 
+        if [[ ! $( curl -sS ${PACKAGES_URL} | wc -l | xargs) -gt 1 ]] || [[ $count -gt 3 ]]; then 
           exit 1 
         fi 
+
+        if [[ $count -gt 3 ]]; then exit 1; fi 
